version: 2.1
orbs:
  go-pkg-test: venus/go-pkg-test@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    executor:
      name: go-pkg-test/default
      tag: "cimg/go:1.18.1"
    steps:
      # Run your orb's commands to validate them.
      - go-pkg-test/setup_env:
          install_ffi: true
      - go-pkg-test/test:
          display-name: example_test_name
          suite: example_test_name
          target: ./
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: venus/go-pkg-test
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
